name: Artifact

on: push

env:
   ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
     - name:  check out the code
     - uses: action/checkout@v2
     - name:  upload the code
     - uses: action/upload-artifact@v2
       with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
