name: Complex Jobs Workflow

on: push

jobs:
     job1:
         name: Linux job
         runs-on: ubuntu-latest
         steps:
         - name: step one
           run: date
     job2:
         name: Windows job
         runs-on: windows-latest
         steps:
         - name: step two
           run: date
     job3:
         name: Mac job
         needs: [job1, job2]
         runs-on: macos-latest
         steps:
         - name: step three
           run: date
